/**
 * @file This file contains the `DraftPanel` component, which displays the generated content and provides editing capabilities.
 * @author Paradroid AI
 * @version 1.0.0
 * 
 * @description This component renders a text area to display the generated content.
 * It shows a visual indicator when content is being generated and provides a way for users to edit the generated content.
 */

import React, { useState, useEffect } from 'react';

/**
 * The draft panel component.
 * This component displays the generated content in a text area and provides editing capabilities.
 * It shows a visual indicator when content is being generated.
 *
 * @param {object} props - The props for the component.
 * @param {object} props.project - The currently selected project object.
 * @param {string} props.content - The generated content to display.
 * @param {boolean} props.isGenerating - Flag indicating if content is currently being generated.
 * @param {string} [props.title="Generated Content"] - The title to display in the panel header.
 * @param {string} [props.description="Content generated by AI will appear here"] - The description to display in the panel.
 * @returns {JSX.Element} The rendered draft panel.
 */
function DraftPanel({ project, content, isGenerating, title = "Generated Content", description = "Content generated by AI will appear here" }) {
    const [draftContent, setDraftContent] = useState(content || '');
    const [isEditing, setIsEditing] = useState(false);

    useEffect(() => {
        setDraftContent(content || '');
    }, [content]);

    const handleSave = async () => {
        if (project && draftContent !== content) {
            try {
                const response = await fetch(`http://localhost:3001/api/projects/${project.id}`, {
                    method: 'PUT',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ generatedContent: draftContent }),
                });
                if (!response.ok) {
                    throw new Error('Failed to save generated content');
                }
                setIsEditing(false);
            } catch (error) {
                console.error('Error saving generated content:', error);
                alert('Failed to save generated content');
            }
        }
    };

    const handleKeyDown = (e) => {
        // Auto-save on Cmd/Ctrl+S
        if ((e.ctrlKey || e.metaKey) && e.key === 's') {
            e.preventDefault();
            handleSave();
        }
    };

    return (
        <div className={`panel ${isGenerating ? 'generating' : ''}`}>
            <div className="panel-header">
                <h3>
                    <span role="img" aria-label="draft">📝</span> {title}
                </h3>
            </div>
            <div className="panel-content">
                <p style={{ color: 'var(--dracula-foreground)' }}>{description}</p>
                <div className="draft-content-wrapper">
                    {isGenerating && (
                        <div className="generating-overlay" style={{
                            position: 'absolute',
                            top: 0,
                            left: 0,
                            right: 0,
                            bottom: 0,
                            background: 'rgba(30, 31, 41, 0.8)',
                            display: 'flex',
                            justifyContent: 'center',
                            alignItems: 'center',
                            zIndex: 10,
                            borderRadius: '6px'
                        }}>
                            <div className="generating-indicator" style={{
                                backgroundColor: 'var(--dracula-selection)',
                                padding: '1rem 1.5rem',
                                borderRadius: '6px',
                                border: '1px solid var(--dracula-divider)',
                                fontWeight: '500',
                                color: 'var(--dracula-foreground)'
                            }}>
                                <div>⏳ Generating content...</div>
                                <div style={{ fontSize: '0.9em', marginTop: '8px', color: 'var(--dracula-comment)' }}>
                                    AI is crafting your content. This may take a few moments.
                                </div>
                            </div>
                        </div>
                    )}
                    <textarea
                        value={draftContent}
                        onChange={(e) => {
                            setDraftContent(e.target.value);
                            setIsEditing(true);
                        }}
                        onBlur={handleSave}
                        onKeyDown={handleKeyDown}
                        placeholder="Generated content will appear here. You can edit this content directly, and changes will be saved automatically."
                        className={`draft-content ${isGenerating ? 'generating' : ''}`}
                        style={{
                            width: '100%',
                            height: '100%',
                            border: '1px solid var(--dracula-divider)',
                            borderRadius: '8px',
                            padding: '16px',
                            fontFamily: 'inherit',
                            fontSize: '1rem',
                            resize: 'none',
                            backgroundColor: 'var(--dracula-background)',
                            color: 'var(--dracula-foreground)',
                            lineHeight: '1.6'
                        }}
                    />
                </div>
                {isEditing && (
                    <div className="save-indicator" style={{ 
                        marginTop: '10px',
                        backgroundColor: 'var(--dracula-card)',
                        borderRadius: '6px',
                        borderLeft: '3px solid var(--dracula-purple)',
                        color: 'var(--dracula-foreground)',
                        padding: '8px'
                    }}>
                        <button 
                            className="btn-primary" 
                            onClick={handleSave}
                            style={{ 
                                marginTop: '10px',
                                backgroundColor: 'var(--dracula-purple)',
                                color: 'var(--dracula-background)',
                                border: 'none',
                                padding: '10px 20px',
                                borderRadius: '8px',
                                cursor: 'pointer',
                                fontSize: '1rem',
                                fontWeight: '500'
                            }}
                        >
                            Save Draft
                        </button>
                        <small style={{ display: 'block', marginTop: '5px', color: 'var(--dracula-comment)' }}>
                            Press Cmd/Ctrl+S to save
                        </small>
                    </div>
                )}
            </div>
        </div>
    );
}

export default DraftPanel;